pipeline {
    agent { label 'nodejs' }

    // Set your OCP project
    environment { APP_NAMESPACE = '...' }

    stages{

        stage('Test'){
            steps {
                sh "node test.js"
            }
        }

        // Add more stages here
        stage('Deploy') {
            steps {
                sh '''
                    oc start-build greeting-metrics \
                    --follow --wait -n rwmhmi-metrics
                '''
            }
        }
    }
}
