pipeline{

   agent any
    
    stages{
        // Add the "Deploy" stage here
        stage('Deploy') {
            steps {
                sh '''
                    oc project rwmhmi-deploy-strategies
                    oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}
